import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";

export const roboto = localFont({
  src: [
    {
      path: './../fonts/Roboto/static/Roboto-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
  ]
})

export const metadata: Metadata = {
  title: "Doodleboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased bg-base text-primary`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
